export const ImageDirectory = {
    '': require('./assets/white.png'),
    'mack': {
        '1': require('./assets/mack/mack1.png'),
        '2': require('./assets/mack/mack2.png'),
        '3': require('./assets/mack/mack3.png'),
        '4': require('./assets/mack/mack4.png'),
        '5': require('./assets/mack/mack5.png'),
        '6': require('./assets/mack/mack6.png'),
        '7': require('./assets/mack/mack7.png'),
        '8': require('./assets/mack/mack8.png'),
        '9': require('./assets/mack/mack9.png'),
        '10': require('./assets/mack/mack10.png'),
        '11': require('./assets/mack/mack11.png'),
        '12': require('./assets/mack/mack12.png'),
        '13': require('./assets/mack/mack13.png'),
        '14': require('./assets/mack/mack14.png'),
    },
    'pickles': {
        '1': require('./assets/pickles/pickles1.png'),
        '2': require('./assets/pickles/pickles2.png'),
        '3': require('./assets/pickles/pickles3.png'),
        '4': require('./assets/pickles/pickles4.png'),
        '5': require('./assets/pickles/pickles5.png'),
        '6': require('./assets/pickles/pickles6.png'),
        '7': require('./assets/pickles/pickles7.png'),
        '8': require('./assets/pickles/pickles8.png'),
        '9': require('./assets/pickles/pickles9.png'),
        '10': require('./assets/pickles/pickles10.png'),
        '11': require('./assets/pickles/pickles11.png'),
        '12': require('./assets/pickles/pickles12.png'),
        '13': require('./assets/pickles/pickles13.png'),
        '14': require('./assets/pickles/pickles14.png'),
    },
    'pumpkin': {
        '1': require('./assets/pumpkin/pumpkin1.png'),
        '2': require('./assets/pumpkin/pumpkin2.png'),
        '3': require('./assets/pumpkin/pumpkin3.png'),
        '4': require('./assets/pumpkin/pumpkin4.png'),
        '5': require('./assets/pumpkin/pumpkin5.png'),
        '6': require('./assets/pumpkin/pumpkin6.png'),
        '7': require('./assets/pumpkin/pumpkin7.png'),
        '8': require('./assets/pumpkin/pumpkin8.png'),
        '9': require('./assets/pumpkin/pumpkin9.png'),
        '10': require('./assets/pumpkin/pumpkin10.png'),
        '11': require('./assets/pumpkin/pumpkin11.png'),
        '12': require('./assets/pumpkin/pumpkin12.png'),
        '13': require('./assets/pumpkin/pumpkin13.png'),
        '14': require('./assets/pumpkin/pumpkin14.png'),
    },
    'shadow': {
        '1': require('./assets/shadow/shadow1.png'),
        '2': require('./assets/shadow/shadow2.png'),
        '3': require('./assets/shadow/shadow3.png'),
        '4': require('./assets/shadow/shadow4.png'),
        '5': require('./assets/shadow/shadow5.png'),
        '6': require('./assets/shadow/shadow6.png'),
        '7': require('./assets/shadow/shadow7.png'),
        '8': require('./assets/shadow/shadow8.png'),
        '9': require('./assets/shadow/shadow9.png'),
        '10': require('./assets/shadow/shadow10.png'),
        '11': require('./assets/shadow/shadow11.png'),
        '12': require('./assets/shadow/shadow12.png'),
        '13': require('./assets/shadow/shadow13.png'),
        '14': require('./assets/shadow/shadow14.png'),
    }
}